-- MySQL Script generated by MySQL Workbench
-- Thứ năm, 15 Tháng 11 Năm 2018 22:33:07 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ilovexeom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ilovexeom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ilovexeom` DEFAULT CHARACTER SET latin1 ;
USE `ilovexeom` ;

-- -----------------------------------------------------
-- Table `ilovexeom`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilovexeom`.`request` (
  `id` INT(11) NOT NULL,
  `idDriver` INT(11) NULL DEFAULT NULL,
  `BeginPlace` VARCHAR(45) NULL DEFAULT NULL,
  `EndPlace` VARCHAR(45) NULL DEFAULT NULL,
  `Time` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ilovexeom`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilovexeom`.`user` (
  `UserName` VARCHAR(45) NOT NULL,
  `PassWord` VARCHAR(45) NOT NULL,
  `id` INT(11) NOT NULL,
  `Name` TEXT NOT NULL,
  `PhoneNumber` INT(11) NOT NULL,
  `Permission` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ilovexeom`.`userRefreshTokenExt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilovexeom`.`userRefreshTokenExt` (
  `UserId` INT(11) NOT NULL,
  `refreshToken` VARCHAR(100) NULL DEFAULT NULL,
  `rdt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
